### ISSUE TITLE
csv reader does not handle incorrect type guesses

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/krangl#10]
Example:
![image](https://cloud.githubusercontent.com/assets/200952/16654796/b62701fc-4457-11e6-9552-b26251dfff7b.png)

**Comment by swuecho** [comment]
also, for tsv will header only. the type is set as int by default, which is not right. 

any method to set the col type manually? Thanks.

**Comment by holgerbrandl** [comment]
Unfortunately not yet.

**Comment by holgerbrandl** [comment]
If no column type info is provided the reader should log guess format info similar to `readr::read_csv`
```
Parsed with column specification:
cols(
  ensembl_gene_id = col_character(),
  external_gene_name = col_character(),
  description = col_character(),
  chromosome_name = col_character(),
  start_position = col_integer(),
  end_position = col_integer(),
  protein_acc = col_character()
)
```

**Comment by holgerbrandl** [comment]
It should also a support a similar model to spec out column types
```
read_tsv("gene_counts.txt",  comment = "#", col_types= cols( .default = col_guess(), Chr = col_character()))
```

**Comment by LeanderG** [comment]
Any ideas on what the API for setting the column types could look like in Kotlin?

Here are some thoughts:
```
val columnTypes = mapOf(
        "id" to IntCol, // would have to add an empty companion object to IntCol and all other column types
        "a" to StringCol,
        "b" to BooleanCol,
        "c" to GuessCol, // would have to add a GuessCol class
        ".default" to StringCol // not sure if this is the best way to set the default type

)

val dataFrame = DataFrame.fromCSV("data.csv", colTypes = columnTypes);
```
Different way of setting the default column type:
```
val dataFrame = DataFrame.fromCSV("data.csv", defaultColType = StringCol);
```

Files without headers could be supported this way later on:
```
val columnTypes = mapOf(
        0 to IntCol,
        7 to StringCol,
        8 to BooleanCol
)
```

**Comment by holgerbrandl** [comment]
Sorry for the delay, I somehow missed your comment.

I like the proposal. In case of missing header we could also follow the convention that the user would need to provide the autogenerated column names `X1`, `X1`, ... to specify types. This is how `readr` (my personal reference here) does it at least  (see [here](http://readr.tidyverse.org/reference/read_delim.html)).

**Comment by LeanderG** [comment]
I implemented the proposal, but I used an enum instead of IntCol, etc.. Is that also ok?
```
val columnTypes = mapOf(
        "id" to ColType.Int,
        "a" to ColType.String,
        "b" to ColType.Boolean,
        "c" to ColType.Guess, 
        ".default" to ColType.String
)
```
I could do a PR after I have written some test cases.

**Comment by holgerbrandl** [comment]
fixed via PR
