### ISSUE TITLE
API Docs link broken

### ISSUE THREAD

**Issue by ss3n** [holgerbrandl/krangl#103]
[API Docs](http://holgerbrandl.github.io/krangl/javadoc/krangl/) link under [Documentation](https://github.com/holgerbrandl/krangl#documentation) seems to be broken and is returning a 404 error:

```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus 
```

I'm not finding an alternative source to the javadoc/KDoc for the library either.

**Comment by holgerbrandl** [comment]
Thanks for the pointer. Your observation actually triggered the migration from gitbook to mdkocs which is way better integrated and the documentation can finally live in the same repo as krangl itself.
