### ISSUE TITLE
How to use Krangl on Android？

### ISSUE THREAD

**Issue by YFChing** [holgerbrandl/krangl#107]
How do I configure krangl on Android？

**Comment by holgerbrandl** [comment]
I have not tried to do so. Generally, you would just need to declare its dependency in your gradle file as described under https://github.com/holgerbrandl/krangl

However, I'm not sure its dependencies https://github.com/holgerbrandl/krangl/blob/master/build.gradle are compatible with android

**Comment by holgerbrandl** [comment]
Partial duplicate of #123. Closed because of inactivity. Feel welcome to reopen if needed.
