### ISSUE TITLE
Friendly 10 minutes guide

### ISSUE THREAD

**Issue by frankgerhardt** [holgerbrandl/krangl#111]
I'm a bit annoyed, sorry. Because of this:

![image](https://user-images.githubusercontent.com/550621/108108187-93ab2300-7090-11eb-8257-fbac90f91dc9.png)

So, the word simply... Aha, simply for you. Aha, not simply for me. I'm stupid. Thanks. 

Jcenter, what is this!? And then 3 links to other places on the Internet, none of them mentioning Jcenter. 

Would it be so hard to add those **exact** ~2 lines to add to the build config so that I could **continue** reading the 10 minutes guide!?

BTW, the 10 minutes are already **over** :-1:

**Comment by holgerbrandl** [comment]
Sorry for the inconvenience. I have adjusted the docs.

You may want to work on your communication skills. This as well as many other repos on GitHub is maintained by volunteers. So please consider a more constructive, humble friendly when pointing out issues or potential improvements. Thank you.
