### ISSUE TITLE
[doc] Missing links

### ISSUE THREAD

**Issue by WojtekPtak** [holgerbrandl/krangl#114]
https://krangl.gitbook.io/docs/getting-started/10_minutes
Missing "Nested data" link

https://krangl.gitbook.io/docs/getting-started/faq
Missing "sources" link in "Further Reading?" section

**Comment by holgerbrandl** [comment]
Thanks for the pointer. gitbook is not used here any longer. The docs now live under http://holgerbrandl.github.io/krangl/

One of your pointers was still legit and is fixed now.
