### ISSUE TITLE
Add cleanNames function!

### ISSUE THREAD

**Issue by carloseguevara** [holgerbrandl/krangl#116]
Hey, I'm not sure about how contributed to this repository, but is a really good idea to add the equivalent janitor clean_names function. Here you have a start idea about this, but I need to read the suggested way to created Kotlin funs and check the rest of the functionalities that have the janitor function.

```
/** Replace current column names with standard lowercased names taking initial names as the base
 * TODO: remove leading and trailing spaces
 * TODO: remove special characters
 * */
fun DataFrame.cleanNames(): DataFrame {
    var df = this
    var newNames = this.names
    newNames = newNames
        .map { it ->
            it
                .toLowerCase()
                .replace(" ", "_")
        }
    var names = this.names.zip(newNames).map { (old, new) -> old to new }.toTypedArray()
    names.map{
        df = df.rename(it)
    }
    return df
}
```

**Comment by carloseguevara** [comment]
With the previous point (I really appreciated your answer), this change to:

```
import krangl.DataFrame
import krangl.readCSV
import krangl.setNames

fun main(args: Array<String>) {
    var df = DataFrame
        .readCSV("data/blind_barber_prepartnership.csv")
        .cleanNames()

    print(df)
}

private fun DataFrame.cleanNames(): DataFrame {
    var df = this
    var newNames = this.names
        .map { it ->
            it
                .toLowerCase()
                .replace(" ", "_")
        }
    return df.setNames(*newNames.toTypedArray())
}
```

**Comment by holgerbrandl** [comment]
The beauty of kotlin is that you can exactly do that (declare an extension on `DataFrame`) without touching the core API.

I'm always a bit reluctant to every possible method to the core API. Here I'm a bit sceptic because _clean naming_ is highly opinionated. There is no consensus afaik.

In https://www.rdocumentation.org/packages/janitor/versions/1.2.0/topics/clean_names they support multiple policies, maybe we could provide something similar/configurable?

**Comment by carloseguevara** [comment]
Yes, sure. That's the idea, create a configurable function but...

I would like to know if it is possible to create something like the Janitor package in Python, where pandas does not have the clean_names function available, but if you import Janitor, the clean_names function is added to pandas objects. Is that the beauty of kotlin? How can contribute with this function here?

```
import pandas as pd
pre_partnership_data = pd.read_csv('prepartnership_data.csv').clean_names()

# AttributeError: 'DataFrame' object has no attribute 'clean_names'
```

```
import pandas as pd
import janitor

pre_partnership_data = pd.read_csv('prepartnership_data.csv').clean_names()
```

**Comment by holgerbrandl** [comment]
Sure. Everyone could build a library with extensions on `DataFrame`. 

For inclusion in krangl, we would need to come up with sensible (or user-provided) namin policies. See my arguments from above.

**Comment by holgerbrandl** [comment]
Closed because of inactivity. Feel welcome to reopen if needed.
