### ISSUE TITLE
add jdbc interface

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/krangl#12]
https://jtablesaw.wordpress.com/2016/06/19/new-load-data-from-any-rdbms/

**Comment by thomasnield** [comment]
This would actually be super helpful

**Comment by holgerbrandl** [comment]
fixed in v0.6 For and example see https://github.com/holgerbrandl/krangl/blob/master/examples/databases/src/main/kotlin/JdbcExample.kt
