### ISSUE TITLE
Timestamp column time not supported

### ISSUE THREAD

**Issue by mrfreitas** [holgerbrandl/krangl#124]
Hello, 

i'm trying to fetch some data from mysql directly into a dataframe and i'm getting this error `Column type 93 is not yet supported by {krangl}` seems that timestamp is not supported. Any idea for a work around without changing the DB.

Also, this will be supported in the future?

Thank you in advance.

**Comment by holgerbrandl** [comment]
Thanks for the pointer. I've fixed this for the next release.
