### ISSUE TITLE
REAL and DOUBLE is not supported when parsing ResultSet

### ISSUE THREAD

**Issue by jcheungshred** [holgerbrandl/krangl#135]
When I pass in resultSet to the following method 

`   
 DataFrame.fromResultSet(result)
`
it errors out and tells me it does not support the following types 7 and 8 which is mapped to REAL and DOUBLE in the java.sql.Types package

to fix it can't we just update the Builder.kt to map Types.DOUBLE and Types.Real to the kotlin Double type to fix this?

**Comment by holgerbrandl** [comment]
Could you provide a PR to adjust the Builder.kt?

**Comment by jcheungshred** [comment]
https://github.com/holgerbrandl/krangl/pull/136 here it is l
