### ISSUE TITLE
Incorrect column type when Long values are present  

### ISSUE THREAD

**Issue by sorokod** [holgerbrandl/krangl#138]
The issue can be observed with the following examples

```kotlin
dataFrameOf("data")(23, 11.2, Long.MAX_VALUE).apply { schema() }
// data  [Integer]  23, 11,2, 9223372036854775807

dataFrameOf("data")(11.2, 23,  Long.MAX_VALUE).apply { schema() }
// data  [Any:Double]  11,2, 23, 9223372036854775807

dataFrameOf("data")(Long.MAX_VALUE, 11.2, 23).apply { schema() }
// data  [Any:Long]  9223372036854775807, 11,2, 23
```
The expected output should be `data  [Dbl]  ... `

Problem is that `krangl` is trying to guess the column type, and the reason it is guessing is because  [isMixedNumeric](https://github.com/holgerbrandl/krangl/blob/d068809478820f9fc671a79fbb71c0ca621b3b2b/src/main/kotlin/krangl/SimpleDataFrame.kt#L500) ignores `Long`s.

How about changing  `isMixedNumeric` to: 
```kotlin
internal fun isMixedNumeric(mutation: List<*>): Boolean {
    for (item in mutation) {
        if (item !is Number?) return false
    }
    return true
}
```
If so, would you like a PR?

**Comment by holgerbrandl** [comment]
Well, spotted. Let's do so.
