### ISSUE TITLE
TableFormula shouldn't have to be specified

### ISSUE THREAD

**Issue by thomasnield** [holgerbrandl/krangl#14]
I don't know if I agree the name `mutate()` is optimal because it implies the `DataFrame` is mutable, which does not seem to be the case because it actually yields a new `DataFrame`. 

```kotlin
package com.swa.np.myproject

import krangl.DataFrame
import krangl.TableFormula
import krangl.fromCSV

fun main(args: Array<String>) {
    val df = DataFrame.fromCSV("C:\\Users\\e98594\\Desktop\\Iter1R1 - New Mktg Day Parameters_Inputs\\Globals\\Connection Builder_V1.csv")

    val newDf = df.mutate(TableFormula("Test") {3})

    print(newDf)
}
```

Also, the documented arguments in the README do not work. You have to explicitly provide a `TableFormula` so I may put in a PR later to fix this.

**Comment by holgerbrandl** [comment]
All `DataFrame`s are immutable by design, and the verbs in `krangl` always create new instances.

Concerning the README examples. They work for me when using the current krangl version 0.4. 

There's one issue with the examples, which is that the examples for `summarize` just run partially in the kotlin REPL. But this is imho a REPL bug, which fails to correctly resolve the `to` method.

**Comment by thomasnield** [comment]
Fair enough on the immutability/mutability topic. Regarding the `TableFormula` needing to be passed, I was missing an import for the right `mutate()`. 

```kotlin
import krangl.DataFrame
import krangl.asStrings
import krangl.fromCSV
import krangl.mutate
import java.time.LocalDate
import java.time.format.DateTimeFormatter

fun main(args: Array<String>) {
    val df = DataFrame.fromCSV("/home/thomas/Desktop/test.csv")

    val converted = df.mutate("CONVERTED_SHIP_DATE") {
        it["SHIP_DATE"].asStrings()
                .map { it?.substring(0,8) }
                .filterNotNull().map { LocalDate.parse(it, DateTimeFormatter.ofPattern("M/d/yyyy")) }
    }

    println(converted)
}
```
