### ISSUE TITLE
krangl vs Kotlin/dataframe

### ISSUE THREAD

**Issue by Burtan** [holgerbrandl/krangl#152]
It seems that jetbrains is developing a similiar library to krangl. Is this some kind of successor?

**Comment by muthenberg** [comment]
Would be interesting to know if krangl will be dying because of this. However for the moment the Kotlin/dataframe seems to be inferiour. I tried to import some CSV data there, which krangl imports perfectly fine and I could not get it to work.

**Comment by holgerbrandl** [comment]
Indeed, my idea is to replace the backend of krangl to become kotlin-dataframe.  So all it will/might provide, are additional functions and/or a more opinionated API.

**Comment by lwhansen** [comment]
Excellent idea. What a boost to the project to have jetbrains" support. Wii take it to next level and will increase adoption. Thanks for all the great work.

**Comment by Burtan** [comment]
> 

Sounds great!

**Comment by muthenberg** [comment]
Thanks for the clarification.
