### ISSUE TITLE
CSV files without header take first line as a header always

### ISSUE THREAD

**Issue by melastmohican** [holgerbrandl/krangl#17]
Apache Commons CSV allows specifying headers.
`
Iterable<CSVRecord> records = CSVFormat.RFC4180.withHeader("ID", "CustomerNo", "Name").parse(in);
for (CSVRecord record : records) {
    String id = record.get("ID");
    String customerNo = record.get("CustomerNo");
    String name = record.get("Name");
}
`

**Comment by holgerbrandl** [comment]
I think you've solved it yourself.
