### ISSUE TITLE
The output of "unite" is inconsistent with the one in tidyr

### ISSUE THREAD

**Issue by fredfeng** [holgerbrandl/krangl#20]
If I run the following program:
    val df: DataFrame = dataFrameOf(
            "id", "Year", "A", "B")(
            1, 2007, 5, 10,
            1, 2008, 2,  0,
            1, 2009, 3, 50,
            2, 2007, 7, 13,
            2, 2008, 5, 17,
            2, 2009, 6, 17
    )
    var dfUnite = df.unite("newCol", mutableListOf("id", "A"))
    dfUnite.print()

I will get the following output from krangl:
Year	B	newCol
2007	10	1_5
2008	0	1_2
2009	50	1_3
2007	13	2_7
2008	17	2_5
2009	17	2_6

However, 
If I use the same api (unite) in tidyr, I will get the following output:
 p4_input1 %>% unite(newCol, id, A)
  newCol Year  B
   1_5 2007 10
    1_2 2008  0
    1_3 2009 50
    2_7 2007 13
    2_5 2008 17
    2_6 2009 17

It seems that the "unite" in tidyr will insert the new column (newCol) to the position of the first column (id) that is being united while Krangl always puts the new column to the last position.

It would be nice if krangl could generate output that is consistent with the original dplyr/tidyr library.

**Comment by holgerbrandl** [comment]
Thanks for the feedback. krangl is deviating from dplyr in a few cases where it seems appropriate. Here, putting in a newly created at the very end seems to give a more consistent API because it is comparable how `mutate` behaves.

So I'd be rather inclined to keep it as it is.
