### ISSUE TITLE
Add options to DataFrame.printDataClassSchema 

### ISSUE THREAD

**Issue by tuesd4y** [holgerbrandl/krangl#25]
The code generated by the DataFrame.printDataClassSchema method is unusable when column headers with spaces in them are used. 

I would suggest either wrapping the column headers in backticks (\`) or converting them to the regular kotlin naming convention (eg: `User Id` to `userId`)

**Comment by holgerbrandl** [comment]
Good point, I'll do so asap.

**Comment by tuesd4y** [comment]
I've already started working on this since I need this functionality for a project I'm currently working on. If it's ok for you I'll probably create a pull request in the next week.

**Comment by holgerbrandl** [comment]
Sounds great, looking forward to it.

**Comment by holgerbrandl** [comment]
Fixed via PR
