### ISSUE TITLE
Is mutate() gone?

### ISSUE THREAD

**Issue by rosenjcb** [holgerbrandl/krangl#26]
I'm on krangl v0.6 and I can't use df.mutate() at all. I looked in DataFrame.kt and I see references to it in comments but no method declaration. I do see it in v0.4 though.

**Comment by holgerbrandl** [comment]
Yes, since most users did not pick up the verb nor its intention, I rather replaced it with `addColumn`/`addColumns`. Sorry for the confusion.

**Comment by rosenjcb** [comment]
Yeah I just used df.addColumn(columnName: String, expression: TableExpression) and it works just the same. Thanks!
