### ISSUE TITLE
Provide a License

### ISSUE THREAD

**Issue by mheider** [holgerbrandl/krangl#31]
Hey there. 
Really liking the approach of krangl. I would like to use it in one of my project, but there is not LICENSE provided. 
You want to publish it under for example MIT or Apache License?
Best Regards!

**Comment by holgerbrandl** [comment]
Shame on me for forgetting the license in the first place

**Comment by holgerbrandl** [comment]
Feel welcome to help to make krangl better. It's more an experiment so far.

**Comment by mheider** [comment]
Thanks man - I will! Starting to experiment with it right now!
