### ISSUE TITLE
Allow specifying return type of DataFrame.get(name: String)

### ISSUE THREAD

**Issue by LeanderG** [holgerbrandl/krangl#32]
It would be nice to have a function on `DataFrame` similar to `operator fun get(name: String): DataCol`, except you can specify the return type with generics.

Calling the function could look this way:
`val d:IntCol = dataFrame.getColumn("d")`
or:
`val d = dataFrame.getColumn<IntCol>("d")`

A possible implementation (only tested for SimpleDataFrame):
```
inline fun <reified T : DataCol> DataFrame.getColumn(name: String): T =
        try {
            val column = cols.first { it.name == name }
            if (column is T) {
                column
            } else {
                val msg = "Could not cast column '${name}' of type '${column::class.simpleName}' to type '${T::class}'"
                throw ColumnTypeCastException(msg)
            }
        } catch (e: NoSuchElementException) {
            throw NoSuchElementException("No column found with name '$name'")
        }
```
The function could also be named `get`, but I find `getColumn` a bit clearer in what it returns. Unfortunately, it can't be called from Java because of `reified`.

Related to this:
I think `get` on `DoubleCol` (`IntCol` etc.) should return a `Double?` (`Int?` etc.) instead of `Any?`.

edit:
I guess you could also just use `dataFrame["d"] as IntCol `

**Comment by holgerbrandl** [comment]
I don't know about your background, but myself coming from R (dplyr/readr), I typically don't assign columns to variables. I rather transform or aggregate tables (see ReadMe.md examples), for which such an inference would not be too helpful. Could you give a more specific example?

To work with the columns you could indeed just use ` df["foo"] as IntCol` to cast the type. There are also shortcuts already to `df["foo"].asInts()` (See https://github.com/holgerbrandl/krangl/blob/76f5ce4affa197ee563d54758114fd841f092b72/src/main/kotlin/krangl/Columns.kt#L292)

Concerning the return type of `get`. We could indeed override it in each impl of `DataCol`. However, this would just help if the user would cast the column. When double-accessing a data-frame, the return type would be still `Any?`:
![image](https://user-images.githubusercontent.com/200952/35923698-423eded4-0c21-11e8-9b62-8d82d7276100.png)

**Comment by LeanderG** [comment]
Sorry for the late response. I wasn't aware of the `df["foo"].asInts()` method. You can close the issue.
