### ISSUE TITLE
How to modify data

### ISSUE THREAD

**Issue by fiddleatwork** [holgerbrandl/krangl#54]
I'm porting some python code to kotlin and I'm stuck.  The python code creates a new column by applying a lambda with some if statements to compare values of columns.  For example add a new column and assign a value if the status is true and assign a different value if the status is false.  It uses assign, apply, and loc to do this.

I cannot find a way to do this with krangl.  Is it possible?

I can't write some code examples because I have to write this on my phone because my company blocks logging into GitHub.

Thanks

**Comment by fiddleatwork** [comment]
I found a way to do it.. I call addColumn and I pass a lambda that does a .rows.map which maps each row to a new column value.  This allows me to use the rows columns as criteria in the formula for the new column.

If this is the correct way to do it, it would be good to add it to the docs, it seems like it'd be a common thing to do.

**Comment by holgerbrandl** [comment]
It is certainly a valid way, and so far there was no more elgant way.

For the next version we could mimic numpy's `where` with something like
```kotlin
fun ExpressionContext.where(booleans: BooleanArray, ifTrue: Any, ifFalse: Any): DataCol {
            val mutationTrue = anyAsColumn(ifTrue, tempColumnName(), nrow)
            val mutationFalse = anyAsColumn(ifFalse, tempColumnName(), nrow)

            val result = booleans.zip(mutationTrue.values()
                   .zip(mutationFalse.values())).map { (first, data) ->
                         if (first) data.first else data.second
                   }

            return handleListErasure(tempColumnName(), result)
        }
```

This would allow to write it down (with optionally vectorized or scalar values) as
```kotlin
irisData.addColumn("trimmed_petal_length") {
     where(it["Petal.Length"] gt 1.3,  1.3 , it["Petal.Length"] )
}
```

Could you imagine a better solution?
