### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oaltun** [holgerbrandl/krangl#55]
Can you add a more friendly installation guide? E.g. for people that are very new to kotlin and gradle?

**Comment by holgerbrandl** [comment]
Fixed via https://github.com/holgerbrandl/krangl-gitbook/commit/ba5656a194b285dffe2a12efa61a5f4487c4b2bb

For the updated version see https://krangl.gitbook.io/docs/#installation

Feel welcome if you have further questions.
