### ISSUE TITLE
Idea: Leverage the Frictionless Table Schema

### ISSUE THREAD

**Issue by jmfayard** [holgerbrandl/krangl#67]
Hello Holger Brandl,

I'm not working in the data science domain but find your talks about it super interesting. 
While browsing the Internet, I came accross this thing that may be interesting for Krangl to leverage

----

The Frictionless Data's Datapackage specification consists of a json file of metadata that accompanies a CSV file that describes column types, versions, sources, and how to validate correctness of the CSV's data. This allows for quite a lot of tooling and workflow improvements to CSV files without mucking with the CSV itself

https://frictionlessdata.io/specs/table-schema/

---

I can imagine how you could generate a data class from that JSON and improve the Krangl workflow

**Comment by holgerbrandl** [comment]
Indeed supported more structured formats for importing/exporting is definitely on the long list of things to do.

**Comment by holgerbrandl** [comment]
I'm closing this ticket due to inactivity. Feel welcome to reopen.
