### ISSUE TITLE
What is plotOf() - documentation issue?

### ISSUE THREAD

**Issue by norandom** [holgerbrandl/krangl#68]
Hi,

I am currently going through the tutorial
https://krangl.gitbook.io/docs/tutorials/statistics 

At the bottom of the page there is a code listing:

```kotlin
// PC1 vs PC2 scatter
plotOf(projection.transpose().array().withIndex()) {
    mark(MarkType.point)
    encoding(x) { value[0] }
    encoding(y) { value[1] }
    encoding(text){ "PC"+index}
}.render()
```

This uses plotOf, which isn't in any of the following packages:

```kotlin
dependencies {
    compile(kotlin("stdlib-jdk8"))

    implementation("com.github.holgerbrandl" + ":" + "kravis" + ":0.5")

    compile("com.github.holgerbrandl" + ":" + "krangl" + ":" + "v0.10.3")
    compile("org.apache.commons" + ":" + "commons-math3" + ":" + "3.6.1")
    compile( "com.github.chen0040" + ":" + "java-glm" + ":" + "1.0.6")
    compile("com.github.haifengl" + ":" + "smile-plot" + ":" + "1.5.2")
    //compile("com.github.haifengl" + ":" + "smile-math" + ":" + "1.5.2")
    //compile("com.github.haifengl" + ":" + "smile-data" + ":" + "1.5.2")
    //compile("com.github.haifengl" + ":" + "smile-interpolation" + ":" + "1.5.2")
    // compile("com.github.haifengl" + ":" + "smile-nlp" + ":" + "1.5.2")
    compile("com.github.haifengl" + ":" + "smile-netlib" + ":" + "1.5.2")
}
```

Can you please help me to either update the call or to find it :)

Best,
Marius

**Comment by holgerbrandl** [comment]
This `plotOf` API  is no longer functional/supported. See https://holgerbrandl.github.io/data_science_with_kotlin/data_science_with_kotlin.html#36 for the pca example and https://github.com/holgerbrandl/kravis for a more general overview.

**Comment by holgerbrandl** [comment]
I'll update the example code asap.

**Comment by norandom** [comment]
Cool, that helps me to continue with the tutorials. Thank you!

**Comment by holgerbrandl** [comment]
Fixed in src, see https://github.com/holgerbrandl/krangl-gitbook/blob/master/tutorials/statistics.md
GitBook rebuild seems to lag for some reason unknown to me.
