### ISSUE TITLE
Support of Long type columns

### ISSUE THREAD

**Issue by davidpedrosa** [holgerbrandl/krangl#69]
Hi.

I'm having problems when trying to work with dataframes created from a CSV that has a column which contains Long values (that is, some values wouldn't fit in an Int).

An easy way to reproduce the issue could be to edit the file src/test/resources/krangl/data/test_header_types.csv and change the following line:
a,1,1,10,TRUE
to
a,1,1,1000000000000000,TRUE

This would break the test `it should have the correct column types`. The automatic type detection would assign it to string, since it doesn't really know of a more specific type. That doesn't work for my use case.

Actually, I'd rather specify the column types when creating the dataframe, but if I take a look to the enumeration ColType I can see there is no Long option:

enum class ColType {
    Int, Double, Boolean, String, Guess
}

Moreover, if I have a look to the subclasses of DataCol (Columns.kt) I can see there is no class for longs, so it seems the changes to acomplish it could be many.

Any workaround that comes to mind?

Thanks.

**Comment by holgerbrandl** [comment]
Indeed there is no Long Support At the moment. Unfortunately, I did not manage to use generics to cover types here (actually I think it's not possible with the current implementation).

Adding it would be straightforward since the implementation is exactly as for Int but with the different Type signature. Feel welcome to submit a PR.

**Comment by davidpedrosa** [comment]
I haven't noticed at the time, but maybe I should have increased the project version. I'm unsure about the release workflow and probably you want to control this anyway, but it would be nice to be able to get an artifact from bintray as opposed to building it from code. Other than that I think we should close the issue.

Thanks.

**Comment by holgerbrandl** [comment]
It's fine like that. I'll take care of that.

**Comment by holgerbrandl** [comment]
Deployed to bintray as v0.11
