### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by PinkFloyded** [holgerbrandl/krangl#73]
Running on Android I get:

> Error: Method name '=' in class 'krangl.Extensions' cannot be represented in dex format on Android

**Comment by holgerbrandl** [comment]
Could you use `to` instead of the overloaded `=` instead to work around the problem? The only solution I could imagine is to remove `=` to make dex happy, but this does not feel like being a fix at all.

**Comment by nick-merlino** [comment]
I tried v0.14 and v0.15 (just released) and I'm still getting this issue when building in Android Studio

**Comment by holgerbrandl** [comment]
Removing it would disable use cases such as 
```
df.summarize(
    "min_age" `=` { it["age"].min() },
    "max_age" `=` { it["age"].max() }
)
```
which I think is how R/python users may want to start using krangl. 

Thus, I'm still not sure if the operator should be removed.
