### ISSUE TITLE
Concatenate multiple DataFrames

### ISSUE THREAD

**Issue by bdudelsack** [holgerbrandl/krangl#80]
Is there a way to concatenate multiple DataFrames? I haven't found any easy possibility to do this. I've also tried to create a new DataFrame with `dataFrameOf` and Lists of DataCols but had no success. 

```kotlin
dataFrameOf(*labs[0].cols.toTypedArray(), *labs[1].cols.toTypedArray())
```

Here is my usecase. I have 5 CSV files with students from the different labs. I want to make a single DataFrame from it with additional column for a lab time (without modifying the CSV files).

```kotlin
val times = listOf("1030", "1215", "1400", "1545", "1730")
val labs = times.map { lab ->
    DataFrame.readCSV("Students-Lab-${lab}.csv", format = CSVFormat.DEFAULT.withHeader().withDelimiter(';'))
        .select("Firstname", "Lastname", "Username")
        .addColumn("Lab") {
            lab
        }
}

/* ... somehow concatenate labs-DataFrames to a single one ... */
```

Here is the way i would concatenate it in Pandas:

```python
students = pd.concat([lab1, lab2, lab3, lab4, lab5], ignore_index=True)
```

Any help is appreciated. Thanks!

**Comment by holgerbrandl** [comment]
Sure,  there are multiple `bindRows` implementations with varying signatures in `Extensions.kt` (i.e. in krangls default namespace). 

Does this cover your use case or do you need something else?

**Comment by bdudelsack** [comment]
Thank you. That was exactly what i needed. I just didn't expect the function to be named like that.

Solution:
```
bindRows(*labs.toTypedArray())
```

**Comment by holgerbrandl** [comment]
Feel welcome if you spot any other missing bits in the API.
