### ISSUE TITLE
Nice to have `toMap` function in DataFrame

### ISSUE THREAD

**Issue by alshan** [holgerbrandl/krangl#86]
This code works for me: 
```
val mpg_df = DataFrame.readCSV("https://jetbrains.bintray.com/lets-plot/mpg.csv")

val dat = (mpg_df.names.filter {it.isNotBlank()}.map { Pair(it, mpg_df.get(it).values())}).toMap()
```
but would be nice to just use:
```
mpg_df.toMap()
```

**Comment by holgerbrandl** [comment]
Thanks for the sharing. You could define an extension function to support this:

```
fun DataFrame.asMap() = names.filter { it.isNotBlank()}.map { Pair(it, get(it).values())}.toMap()
```

Clearly krangl's API needs to be extended to cover more use-cases, but unless you could elaborate more on the specific usecase, I'd think that such extension does not need to be part of the core API.

**Comment by alshan** [comment]
Here is my use-case: https://github.com/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/geom_smooth.ipynb

I read CSV file to krangl DataFrame and then have to convert it to a regular Map to pass to Lets-Plot as data parameter.
Lets-Plot is not dependent on Krangl but even if it were dependent creation of such an extension does look like a leaky abstraction to me. 

The most reasonable place to put the `toMap` extension IMO would be Krangl itself.

**Comment by alshan** [comment]
Another use-case and the pain is right here 
![image](https://user-images.githubusercontent.com/4430922/86296437-c9190400-bbc6-11ea-943d-7a4c9b14eb21.png)

https://jaxenter.com/kotlin-jupyter-notebook-172202.html

**Comment by holgerbrandl** [comment]
Great examples. I took the liberty to disable the `isNotBlank` filter. Imho either `krangl` should not support empty column names (similar to how dplyr does it). Or, an empty column name (just one, because names must be unique by design) is legit, and should be preserved when doing `toMap`. But I guess this would be a different ticket.

**Comment by alshan** [comment]
My understanding was that no-name column was the index. As map don't have index I've dropped it.

**Comment by holgerbrandl** [comment]
There is no equivalent to pandas indices in krangl. I personally found the index concept always confusing compared to dplyr which works great (if not better) without confronting the user with a similar index-concept. 

So in krangl, we enforce unqique columns already (following dplyr's lead), but we currently support an empty string as column name. However, I can't imagine any usecase for such a feature, so I'd be more in favor of enforcing not-null not-empty column names.

**Comment by holgerbrandl** [comment]
Btw, how did you write https://jetbrains.bintray.com/lets-plot/mpg.csv ? I've noticed that the latest version of the used csv parsing library commons-csv can not handle it because of https://issues.apache.org/jira/browse/CSV-257 and I'd like to comment on it by pointing to your example file.

**Comment by alshan** [comment]
I really couldn't recall now. Please feel free to point at it. I believe we've checked the license before using it.
