### ISSUE TITLE
Make DataCol type casting possible

### ISSUE THREAD

**Issue by Linux4win** [holgerbrandl/krangl#95]
Currently, it does not appear to be possible to e.g. cast a StringCol to an IntCol. Since DataCols may contain data of various types, it should be possible to cast a DataCol that previously contained strings to an IntCol after the "actual" strings have been filtered out (and only integers in strings are left).

**Expected behaviour**
It is possible to cast a subclass(?) of DataCol to a different subclass of DataCol

**Actual behaviour**
It does not seem to be possible to cast a subclass of DataCol to a different subclass of DataCol.

**Comment by holgerbrandl** [comment]
Feel welcome to correct me, but I think that we can not use a kotlin typecast with `as` here. 

This is how I see 
is how I think we could do it now  and how we could possibly extend it:

```
        // type conversion with current API
        irisData
                .addColumn("str") { "3" }
                .addColumn("int") { it["str"].map<String> { it.toInt() } }
                .schema()


        // with extension (could/should we add this to API?)
        fun DataCol.toInt(): List<Any?> = map<String> { it.toInt() }

        irisData
                .addColumn("str") { "3" }
                .addColumn("int") { it["str"].toInt() }
                .schema()

        // implicit conversions        
        irisData
                .addColumn("str") { "3" }
                .addColumn("int") { it["str"].toInt() }
                
                // supported already
                .addColumn("impl_3") {   it["str"] + it["int"] }

                
                // not supported but should be imho
                .addColumn("impl_1") { it["str"]  + 3 }
                .addColumn("impl_3") {   it["int"] + it["str"] }
                .addColumn("impl_2") {   3 + it["str"] }
                .schema()
```
Clearly, we need support for `Number` and not just `Int` here.

What do you think

**Comment by holgerbrandl** [comment]
And btw, the reason why we need to do `map<String>` is primarily to cast type and to support missing values.

**Comment by Linux4win** [comment]
Clearly I was wrong about not being able to _convert_ DataCols, (I probably explained my issue poorly) the way you said was currently possible seems to work.
